# Generated by Django 6.1 on 2026-08-08 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chair_ru', models.CharField(default='', max_length=200, verbose_name='руководитель')),
                ('chair_en', models.CharField(blank=True, default='', max_length=200)),
                ('chair_title_ru', models.CharField(default='', max_length=200, verbose_name='звание руководителя')),
                ('chair_title_en', models.CharField(blank=True, default='', max_length=200)),
                ('secretary_ru', models.CharField(default='', max_length=200, verbose_name='секретарь')),
                ('secretary_en', models.CharField(blank=True, default='', max_length=200)),
                ('secretary_title_ru', models.CharField(default='', max_length=200, verbose_name='звание секретаря')),
                ('secretary_title_en', models.CharField(blank=True, default='', max_length=200)),
                ('email', models.EmailField(default='seminar@cosmos.ru', max_length=254, verbose_name='почта семинара')),
                ('address_ru', models.CharField(default='', max_length=300, verbose_name='адрес')),
                ('address_en', models.CharField(blank=True, default='', max_length=300)),
                ('registration_lead_hours', models.PositiveSmallIntegerField(default=48, verbose_name='закрывать заявки за N часов до начала')),
                ('notify_on_registration', models.BooleanField(default=True, verbose_name='письмо о каждой заявке')),
                ('notify_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='куда слать уведомления')),
                ('privacy_policy_url', models.CharField(blank=True, default='', max_length=300, verbose_name='ссылка на политику обработки ПД')),
            ],
            options={
                'verbose_name': 'настройки сайта',
                'verbose_name_plural': 'настройки сайта',
            },
        ),
    ]
