# Generated by Django 6.1 on 2026-08-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='privacy_policy_text',
            field=models.TextField(blank=True, default='', help_text='Согласовывается заказчиком. Пока пусто, на странице стоит заглушка.', verbose_name='текст согласия на обработку ПД'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='retention_months',
            field=models.PositiveSmallIntegerField(default=6, help_text='По истечении срока заявки удаляет команда purge_registrations.', verbose_name='хранить заявки, месяцев после заседания'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='privacy_policy_url',
            field=models.CharField(blank=True, default='', help_text='Если заполнено, используется вместо страницы на сайте.', max_length=300, verbose_name='внешняя ссылка на политику обработки ПД'),
        ),
    ]
