# Generated by Django 6.1 on 2026-08-22 20:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cache_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='privacy_policy_text',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='privacy_policy_url',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='online_link_captcha',
            field=models.BooleanField(default=True, help_text='Ссылка на видеоконференцию отдаётся после ввода кода с картинки. Пройденная проверка помнится два часа.', verbose_name='проверять посетителя перед показом ссылки на трансляцию'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='privacy_policy_file',
            field=models.FileField(blank=True, help_text='PDF. Открывается по ссылке «Обработка персональных данных» в подвале и в форме записи. Пока файла нет, на странице стоит заглушка.', upload_to='policy/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='документ согласия на обработку ПД'),
        ),
    ]
