# Generated by Django 6.1 on 2026-09-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_privacy_policy_file_and_link_captcha'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='foreign_extra_lead_hours',
            field=models.PositiveSmallIntegerField(default=48, help_text='Считается от общего срока приёма заявок. Только для очного участия.', verbose_name='закрывать очные заявки не граждан РФ на N часов раньше'),
        ),
    ]
