# Generated by Django 6.1 on 2026-08-12 17:25

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seminars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('organization', models.CharField(max_length=300, verbose_name='организация')),
                ('position', models.CharField(blank=True, default='', max_length=200, verbose_name='должность')),
                ('email', models.EmailField(max_length=254, verbose_name='контактная почта')),
                ('attendance', models.CharField(choices=[('onsite', 'Очно'), ('online', 'Онлайн')], default='onsite', max_length=10, verbose_name='формат участия')),
                ('pass_status', models.CharField(choices=[('not_needed', 'не требуется'), ('pending', 'в обработке'), ('issued', 'оформлен')], default='not_needed', max_length=12, verbose_name='пропуск')),
                ('consent_pd', models.BooleanField(default=False, verbose_name='согласие на обработку ПД')),
                ('consent_at', models.DateTimeField(blank=True, null=True, verbose_name='момент согласия')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_hash', models.CharField(blank=True, default='', editable=False, max_length=32)),
                ('seminar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='seminars.seminar', verbose_name='заседание')),
            ],
            options={
                'verbose_name': 'заявка',
                'verbose_name_plural': 'заявки',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['seminar', '-created_at'], name='registratio_seminar_24017b_idx')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('email'), models.F('seminar'), name='unique_registration_per_seminar')],
            },
        ),
    ]
