# Generated by Django 6.1 on 2026-09-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='is_foreign',
            field=models.BooleanField(default=False, verbose_name='не гражданин РФ'),
        ),
    ]
