# Generated by Django 6.1 on 2026-08-15 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seminars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegacySeminarLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=20, unique=True, verbose_name='узел старого сайта')),
                ('legacy_slug', models.CharField(blank=True, max_length=220, verbose_name='адрес на старом сайте')),
                ('legacy_url', models.URLField(max_length=500, verbose_name='страница-источник')),
                ('imported_at', models.DateTimeField(auto_now=True, verbose_name='импортировано')),
                ('seminar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_link', to='seminars.seminar', verbose_name='заседание')),
            ],
            options={
                'verbose_name': 'связь со старым сайтом',
                'verbose_name_plural': 'связи со старым сайтом',
                'ordering': ['node_id'],
            },
        ),
    ]
