# Generated by Django 6.1 on 2026-08-10 23:30

import apps.core.i18n
import datetime
import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name_ru', models.CharField(max_length=200, verbose_name='ФИО')),
                ('full_name_en', models.CharField(blank=True, default='', max_length=200)),
                ('affiliation_ru', models.CharField(blank=True, default='', max_length=400, verbose_name='должность и организация')),
                ('affiliation_en', models.CharField(blank=True, default='', max_length=400)),
                ('photo', models.ImageField(blank=True, upload_to='speakers/', verbose_name='фото')),
            ],
            options={
                'verbose_name': 'докладчик',
                'verbose_name_plural': 'докладчики',
                'ordering': ['full_name_ru'],
            },
            bases=(apps.core.i18n.TranslatedMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=40, unique=True, verbose_name='код')),
                ('name_ru', models.CharField(max_length=120, verbose_name='название')),
                ('name_en', models.CharField(blank=True, default='', max_length=120)),
                ('short_ru', models.CharField(max_length=40, verbose_name='короткое название')),
                ('short_en', models.CharField(blank=True, default='', max_length=40)),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='порядок')),
            ],
            options={
                'verbose_name': 'тематика',
                'verbose_name_plural': 'тематика',
                'ordering': ['order', 'name_ru'],
            },
            bases=(apps.core.i18n.TranslatedMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Seminar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='адрес')),
                ('date', models.DateField(verbose_name='дата')),
                ('start_time', models.TimeField(default=datetime.time(11, 0), verbose_name='время начала')),
                ('title_ru', models.CharField(max_length=500, verbose_name='тема заседания')),
                ('title_en', models.CharField(blank=True, default='', max_length=500)),
                ('abstract_ru', models.TextField(blank=True, default='', verbose_name='аннотация')),
                ('abstract_en', models.TextField(blank=True, default='')),
                ('place_ru', models.CharField(blank=True, default='', max_length=300, verbose_name='место')),
                ('place_en', models.CharField(blank=True, default='', max_length=300)),
                ('seminar_format', models.CharField(choices=[('onsite', 'Только очно'), ('online', 'Только онлайн'), ('hybrid', 'Очно и онлайн')], default='hybrid', max_length=10, verbose_name='формат')),
                ('online_url', models.URLField(blank=True, default='', verbose_name='ссылка на видеоконференцию')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликован'), ('hidden', 'Скрыт')], default='draft', max_length=10, verbose_name='статус')),
                ('pass_required', models.BooleanField(default=True, verbose_name='нужен пропуск')),
                ('registration_closes_at', models.DateTimeField(blank=True, help_text='Если не задано, считается по умолчанию из настроек сайта.', null=True, verbose_name='приём заявок до')),
                ('poster', models.ImageField(blank=True, upload_to='posters/', verbose_name='постер')),
                ('search_text', models.TextField(blank=True, default='', editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seminars', to='seminars.topic', verbose_name='тематика')),
            ],
            options={
                'verbose_name': 'заседание',
                'verbose_name_plural': 'заседания',
                'ordering': ['-date'],
            },
            bases=(apps.core.i18n.TranslatedMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='порядок')),
                ('title_ru', models.CharField(max_length=500, verbose_name='название доклада')),
                ('title_en', models.CharField(blank=True, default='', max_length=500)),
                ('abstract_ru', models.TextField(blank=True, default='', verbose_name='аннотация')),
                ('abstract_en', models.TextField(blank=True, default='')),
                ('seminar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talks', to='seminars.seminar', verbose_name='заседание')),
            ],
            options={
                'verbose_name': 'доклад',
                'verbose_name_plural': 'доклады',
                'ordering': ['order', 'id'],
            },
            bases=(apps.core.i18n.TranslatedMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TalkSpeaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='talk_links', to='seminars.speaker')),
                ('talk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaker_links', to='seminars.talk')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='talk',
            name='speakers',
            field=models.ManyToManyField(related_name='talks', through='seminars.TalkSpeaker', to='seminars.speaker', verbose_name='докладчики'),
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('abstract', 'Аннотация'), ('slides', 'Презентация'), ('video', 'Видеозапись'), ('other', 'Материал')], default='abstract', max_length=10, verbose_name='тип')),
                ('title_ru', models.CharField(blank=True, default='', max_length=200, verbose_name='подпись')),
                ('title_en', models.CharField(blank=True, default='', max_length=200)),
                ('file', models.FileField(blank=True, upload_to='materials/%Y/', verbose_name='файл')),
                ('url', models.URLField(blank=True, default='', verbose_name='ссылка')),
                ('seminar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='seminars.seminar', verbose_name='заседание')),
                ('talk', models.ForeignKey(blank=True, help_text='Пусто — материал относится ко всему заседанию.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='seminars.talk', verbose_name='доклад')),
            ],
            options={
                'verbose_name': 'материал',
                'verbose_name_plural': 'материалы',
                'ordering': ['kind', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('file', ''), _negated=True), models.Q(('url', ''), _negated=True), _connector='OR'), name='material_has_file_or_url')],
            },
            bases=(apps.core.i18n.TranslatedMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='talkspeaker',
            constraint=models.UniqueConstraint(fields=('talk', 'speaker'), name='unique_talk_speaker'),
        ),
        migrations.AddIndex(
            model_name='seminar',
            index=models.Index(fields=['status', '-date'], name='seminars_se_status_7356b8_idx'),
        ),
        migrations.AddIndex(
            model_name='seminar',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.search.SearchVector('search_text', config='russian'), name='seminar_search_gin'),
        ),
    ]
