# Generated by Django 6.1 on 2026-08-15 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='url',
            field=models.URLField(blank=True, default='', max_length=1000, verbose_name='ссылка'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='online_url',
            field=models.URLField(blank=True, default='', max_length=1000, verbose_name='ссылка на видеоконференцию'),
        ),
    ]
