# Generated by Django 6.1 on 2026-08-08 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskRecord',
            fields=[
                ('id', models.CharField(editable=False, max_length=32, primary_key=True, serialize=False)),
                ('task_path', models.TextField(verbose_name='путь к задаче')),
                ('args', models.JSONField(blank=True, default=list)),
                ('kwargs', models.JSONField(blank=True, default=dict)),
                ('priority', models.SmallIntegerField(default=0)),
                ('queue_name', models.CharField(default='default', max_length=64)),
                ('backend_alias', models.CharField(default='default', max_length=64)),
                ('takes_context', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('READY', 'READY'), ('RUNNING', 'RUNNING'), ('FAILED', 'FAILED'), ('SUCCESSFUL', 'SUCCESSFUL')], default='READY', max_length=16)),
                ('run_after', models.DateTimeField(blank=True, null=True)),
                ('enqueued_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('last_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('worker_ids', models.JSONField(blank=True, default=list)),
                ('return_value', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'фоновая задача',
                'verbose_name_plural': 'фоновые задачи',
                'indexes': [models.Index(fields=['status', 'queue_name', 'run_after'], name='notificatio_status_dbe0a2_idx'), models.Index(fields=['-enqueued_at'], name='notificatio_enqueue_3efab9_idx')],
            },
        ),
    ]
